export default {
    defaultVariant: 'primary',
    fixed: {
        root: '',
        navWrap: '',
        nav: '',
        link: '',
        linkActive: '',
        linkInactive: '',
        content: 'mt-8',
        tabItem: '',
    },
    variants: {
        primary: {
            root: '',
            navWrap: 'border-b border-gray-200',
            nav: '-mb-px flex space-x-8',
            link: 'whitespace-nowrap py-4 px-1 border-b-2 font-medium text-sm',
            linkActive: 'border-blue-500 text-blue-600',
            linkInactive: 'text-gray-500 border-transparent hover:text-gray-700 hover:border-gray-300',
            content: '',
            tabItem: '',
        },
        secondary: {
            root: '',
            navWrap: 'bg-gray-300 rounded-lg p-2',
            nav: 'flex space-x-3',
            link: 'whitespace-nowrap py-1 px-2 font-medium text-sm rounded-md',
            linkActive: 'border-gray-500 text-gray-600 bg-white',
            linkInactive: 'text-gray-400 border-transparent hover:text-gray-700 hover:border-gray-300',
            content: '',
            tabItem: '',
        },
    },
};
