export default {
    defaultVariant: 'primary',
    fixed: {
        backdrop: 'bg-gray-700 bg-opacity-75',
        panel: 'flex flex-col bg-white shadow-xl overflow-y-auto',
        header: 'p-6',
        title: 'text-lg font-medium text-white',
        description: 'text-sm',
        descriptionWrapper: 'mt-1',
        btnClose: '',
        container: 'my-6 relative flex-1 px-4 sm:px-6',
    },
    variants: {
        primary: {
            backdrop: '',
            panel: '',
            header: 'bg-blue-700',
            title: 'text-blue-50',
            description: 'text-blue-300',
            descriptionWrapper: '',
            btnClose: 'text-blue-50',
            container: '',
        },
        secondary: {
            backdrop: '',
            panel: '',
            header: 'bg-gray-200',
            title: 'text-gray-700',
            description: 'text-gray-600',
            descriptionWrapper: '',
            btnClose: 'text-gray-700',
            container: '',
        },
    },
};
