<template>
    <div>
        <h3 class="text-lg font-bold mb-2">
            Buttons
        </h3>

        <div class="grid gap-4">
            <div
                v-for="(button, index) in buttons"
                :key="index"
            >
                <TwButton
                    v-for="(b, idx) in button"
                    :key="idx"
                    :theme="b.theme"
                    :color="b.color"
                    :pill="b.pill"
                    :outline="b.outline"
                    :size="b.size"
                    :class="b.class"
                >
                    Button
                </TwButton>
            </div>
        </div>
    </div>
</template>

<script>
    import TwButton from '@/components/TwButton';

    export default {
        name: 'Buttons',

        components: {
            TwButton,
        },

        data() {
            return {
                buttons: [
                    [
                        { size: 'xs', theme: 'light', color: 'gray', pill: false, outline: false, class: null },
                        { size: 'xs', theme: 'light', color: 'cool-gray', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'light', color: 'red', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'light', color: 'orange', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'light', color: 'yellow', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'light', color: 'green', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'light', color: 'teal', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'light', color: 'indigo', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'light', color: 'blue', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'light', color: 'purple', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'light', color: 'pink', pill: false, outline: false, class: 'mx-1' },
                    ],
                    [
                        { size: 'xs', theme: 'light', color: 'gray', pill: true, outline: false, class: null },
                        { size: 'xs', theme: 'light', color: 'cool-gray', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'light', color: 'red', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'light', color: 'orange', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'light', color: 'yellow', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'light', color: 'green', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'light', color: 'teal', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'light', color: 'indigo', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'light', color: 'blue', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'light', color: 'purple', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'light', color: 'pink', pill: true, outline: false, class: 'mx-1' },
                    ],
                    [
                        { size: 'xs', theme: 'light', color: 'gray', pill: false, outline: true, class: null },
                        { size: 'xs', theme: 'light', color: 'cool-gray', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'light', color: 'red', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'light', color: 'orange', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'light', color: 'yellow', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'light', color: 'green', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'light', color: 'teal', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'light', color: 'indigo', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'light', color: 'blue', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'light', color: 'purple', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'light', color: 'pink', pill: false, outline: true, class: 'mx-1' },
                    ],
                    [
                        { size: 'xs', theme: 'light', color: 'gray', pill: true, outline: true, class: null },
                        { size: 'xs', theme: 'light', color: 'cool-gray', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'light', color: 'red', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'light', color: 'orange', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'light', color: 'yellow', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'light', color: 'green', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'light', color: 'teal', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'light', color: 'indigo', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'light', color: 'blue', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'light', color: 'purple', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'light', color: 'pink', pill: true, outline: true, class: 'mx-1' },
                    ],
                    [
                        { size: 'xs', theme: 'dark', color: 'gray', pill: false, outline: false, class: null },
                        { size: 'xs', theme: 'dark', color: 'cool-gray', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'dark', color: 'red', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'dark', color: 'orange', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'dark', color: 'yellow', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'dark', color: 'green', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'dark', color: 'teal', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'dark', color: 'indigo', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'dark', color: 'blue', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'dark', color: 'purple', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'dark', color: 'pink', pill: false, outline: false, class: 'mx-1' },
                    ],
                    [
                        { size: 'xs', theme: 'dark', color: 'gray', pill: true, outline: false, class: null },
                        { size: 'xs', theme: 'dark', color: 'cool-gray', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'dark', color: 'red', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'dark', color: 'orange', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'dark', color: 'yellow', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'dark', color: 'green', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'dark', color: 'teal', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'dark', color: 'indigo', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'dark', color: 'blue', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'dark', color: 'purple', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'dark', color: 'pink', pill: true, outline: false, class: 'mx-1' },
                    ],
                    [
                        { size: 'xs', theme: 'dark', color: 'gray', pill: false, outline: true, class: null },
                        { size: 'xs', theme: 'dark', color: 'cool-gray', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'dark', color: 'red', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'dark', color: 'orange', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'dark', color: 'yellow', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'dark', color: 'green', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'dark', color: 'teal', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'dark', color: 'indigo', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'dark', color: 'blue', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'dark', color: 'purple', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'dark', color: 'pink', pill: false, outline: true, class: 'mx-1' },
                    ],
                    [
                        { size: 'xs', theme: 'dark', color: 'gray', pill: true, outline: true, class: null },
                        { size: 'xs', theme: 'dark', color: 'cool-gray', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'dark', color: 'red', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'dark', color: 'orange', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'dark', color: 'yellow', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'dark', color: 'green', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'dark', color: 'teal', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'dark', color: 'indigo', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'dark', color: 'blue', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'dark', color: 'purple', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'dark', color: 'pink', pill: true, outline: true, class: 'mx-1' },
                    ],
                    [
                        { size: 'xs', theme: 'darker', color: 'gray', pill: false, outline: false, class: null },
                        { size: 'xs', theme: 'darker', color: 'cool-gray', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'darker', color: 'red', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'darker', color: 'orange', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'darker', color: 'yellow', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'darker', color: 'green', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'darker', color: 'teal', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'darker', color: 'indigo', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'darker', color: 'blue', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'darker', color: 'purple', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'darker', color: 'pink', pill: false, outline: false, class: 'mx-1' },
                    ],
                    [
                        { size: 'xs', theme: 'darker', color: 'gray', pill: true, outline: false, class: null },
                        { size: 'xs', theme: 'darker', color: 'cool-gray', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'darker', color: 'red', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'darker', color: 'orange', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'darker', color: 'yellow', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'darker', color: 'green', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'darker', color: 'teal', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'darker', color: 'indigo', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'darker', color: 'blue', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'darker', color: 'purple', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xs', theme: 'darker', color: 'pink', pill: true, outline: false, class: 'mx-1' },
                    ],
                    [
                        { size: 'xs', theme: 'darker', color: 'gray', pill: false, outline: true, class: null },
                        { size: 'xs', theme: 'darker', color: 'cool-gray', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'darker', color: 'red', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'darker', color: 'orange', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'darker', color: 'yellow', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'darker', color: 'green', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'darker', color: 'teal', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'darker', color: 'indigo', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'darker', color: 'blue', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'darker', color: 'purple', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'darker', color: 'pink', pill: false, outline: true, class: 'mx-1' },
                    ],
                    [
                        { size: 'xs', theme: 'darker', color: 'gray', pill: true, outline: true, class: null },
                        { size: 'xs', theme: 'darker', color: 'cool-gray', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'darker', color: 'red', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'darker', color: 'orange', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'darker', color: 'yellow', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'darker', color: 'green', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'darker', color: 'teal', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'darker', color: 'indigo', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'darker', color: 'blue', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'darker', color: 'purple', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xs', theme: 'darker', color: 'pink', pill: true, outline: true, class: 'mx-1' },
                    ],
                    [
                        { size: 'sm', theme: 'light', color: 'gray', pill: false, outline: false, class: null },
                        { size: 'sm', theme: 'light', color: 'cool-gray', pill: false, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'light', color: 'red', pill: false, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'light', color: 'orange', pill: false, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'light', color: 'yellow', pill: false, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'light', color: 'green', pill: false, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'light', color: 'teal', pill: false, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'light', color: 'indigo', pill: false, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'light', color: 'blue', pill: false, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'light', color: 'purple', pill: false, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'light', color: 'pink', pill: false, outline: false, class: 'mx-1' },
                    ],
                    [
                        { size: 'sm', theme: 'light', color: 'gray', pill: true, outline: false, class: null },
                        { size: 'sm', theme: 'light', color: 'cool-gray', pill: true, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'light', color: 'red', pill: true, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'light', color: 'orange', pill: true, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'light', color: 'yellow', pill: true, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'light', color: 'green', pill: true, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'light', color: 'teal', pill: true, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'light', color: 'indigo', pill: true, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'light', color: 'blue', pill: true, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'light', color: 'purple', pill: true, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'light', color: 'pink', pill: true, outline: false, class: 'mx-1' },
                    ],
                    [
                        { size: 'sm', theme: 'light', color: 'gray', pill: false, outline: true, class: null },
                        { size: 'sm', theme: 'light', color: 'cool-gray', pill: false, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'light', color: 'red', pill: false, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'light', color: 'orange', pill: false, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'light', color: 'yellow', pill: false, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'light', color: 'green', pill: false, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'light', color: 'teal', pill: false, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'light', color: 'indigo', pill: false, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'light', color: 'blue', pill: false, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'light', color: 'purple', pill: false, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'light', color: 'pink', pill: false, outline: true, class: 'mx-1' },
                    ],
                    [
                        { size: 'sm', theme: 'light', color: 'gray', pill: true, outline: true, class: null },
                        { size: 'sm', theme: 'light', color: 'cool-gray', pill: true, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'light', color: 'red', pill: true, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'light', color: 'orange', pill: true, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'light', color: 'yellow', pill: true, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'light', color: 'green', pill: true, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'light', color: 'teal', pill: true, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'light', color: 'indigo', pill: true, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'light', color: 'blue', pill: true, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'light', color: 'purple', pill: true, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'light', color: 'pink', pill: true, outline: true, class: 'mx-1' },
                    ],
                    [
                        { size: 'sm', theme: 'dark', color: 'gray', pill: false, outline: false, class: null },
                        { size: 'sm', theme: 'dark', color: 'cool-gray', pill: false, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'dark', color: 'red', pill: false, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'dark', color: 'orange', pill: false, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'dark', color: 'yellow', pill: false, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'dark', color: 'green', pill: false, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'dark', color: 'teal', pill: false, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'dark', color: 'indigo', pill: false, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'dark', color: 'blue', pill: false, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'dark', color: 'purple', pill: false, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'dark', color: 'pink', pill: false, outline: false, class: 'mx-1' },
                    ],
                    [
                        { size: 'sm', theme: 'dark', color: 'gray', pill: true, outline: false, class: null },
                        { size: 'sm', theme: 'dark', color: 'cool-gray', pill: true, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'dark', color: 'red', pill: true, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'dark', color: 'orange', pill: true, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'dark', color: 'yellow', pill: true, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'dark', color: 'green', pill: true, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'dark', color: 'teal', pill: true, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'dark', color: 'indigo', pill: true, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'dark', color: 'blue', pill: true, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'dark', color: 'purple', pill: true, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'dark', color: 'pink', pill: true, outline: false, class: 'mx-1' },
                    ],
                    [
                        { size: 'sm', theme: 'dark', color: 'gray', pill: false, outline: true, class: null },
                        { size: 'sm', theme: 'dark', color: 'cool-gray', pill: false, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'dark', color: 'red', pill: false, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'dark', color: 'orange', pill: false, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'dark', color: 'yellow', pill: false, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'dark', color: 'green', pill: false, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'dark', color: 'teal', pill: false, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'dark', color: 'indigo', pill: false, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'dark', color: 'blue', pill: false, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'dark', color: 'purple', pill: false, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'dark', color: 'pink', pill: false, outline: true, class: 'mx-1' },
                    ],
                    [
                        { size: 'sm', theme: 'dark', color: 'gray', pill: true, outline: true, class: null },
                        { size: 'sm', theme: 'dark', color: 'cool-gray', pill: true, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'dark', color: 'red', pill: true, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'dark', color: 'orange', pill: true, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'dark', color: 'yellow', pill: true, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'dark', color: 'green', pill: true, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'dark', color: 'teal', pill: true, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'dark', color: 'indigo', pill: true, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'dark', color: 'blue', pill: true, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'dark', color: 'purple', pill: true, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'dark', color: 'pink', pill: true, outline: true, class: 'mx-1' },
                    ],
                    [
                        { size: 'sm', theme: 'darker', color: 'gray', pill: false, outline: false, class: null },
                        { size: 'sm', theme: 'darker', color: 'cool-gray', pill: false, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'darker', color: 'red', pill: false, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'darker', color: 'orange', pill: false, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'darker', color: 'yellow', pill: false, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'darker', color: 'green', pill: false, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'darker', color: 'teal', pill: false, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'darker', color: 'indigo', pill: false, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'darker', color: 'blue', pill: false, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'darker', color: 'purple', pill: false, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'darker', color: 'pink', pill: false, outline: false, class: 'mx-1' },
                    ],
                    [
                        { size: 'sm', theme: 'darker', color: 'gray', pill: true, outline: false, class: null },
                        { size: 'sm', theme: 'darker', color: 'cool-gray', pill: true, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'darker', color: 'red', pill: true, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'darker', color: 'orange', pill: true, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'darker', color: 'yellow', pill: true, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'darker', color: 'green', pill: true, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'darker', color: 'teal', pill: true, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'darker', color: 'indigo', pill: true, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'darker', color: 'blue', pill: true, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'darker', color: 'purple', pill: true, outline: false, class: 'mx-1' },
                        { size: 'sm', theme: 'darker', color: 'pink', pill: true, outline: false, class: 'mx-1' },
                    ],
                    [
                        { size: 'sm', theme: 'darker', color: 'gray', pill: false, outline: true, class: null },
                        { size: 'sm', theme: 'darker', color: 'cool-gray', pill: false, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'darker', color: 'red', pill: false, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'darker', color: 'orange', pill: false, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'darker', color: 'yellow', pill: false, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'darker', color: 'green', pill: false, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'darker', color: 'teal', pill: false, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'darker', color: 'indigo', pill: false, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'darker', color: 'blue', pill: false, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'darker', color: 'purple', pill: false, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'darker', color: 'pink', pill: false, outline: true, class: 'mx-1' },
                    ],
                    [
                        { size: 'sm', theme: 'darker', color: 'gray', pill: true, outline: true, class: null },
                        { size: 'sm', theme: 'darker', color: 'cool-gray', pill: true, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'darker', color: 'red', pill: true, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'darker', color: 'orange', pill: true, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'darker', color: 'yellow', pill: true, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'darker', color: 'green', pill: true, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'darker', color: 'teal', pill: true, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'darker', color: 'indigo', pill: true, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'darker', color: 'blue', pill: true, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'darker', color: 'purple', pill: true, outline: true, class: 'mx-1' },
                        { size: 'sm', theme: 'darker', color: 'pink', pill: true, outline: true, class: 'mx-1' },
                    ],
                    [
                        { size: 'md', theme: 'light', color: 'gray', pill: false, outline: false, class: null },
                        { size: 'md', theme: 'light', color: 'cool-gray', pill: false, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'light', color: 'red', pill: false, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'light', color: 'orange', pill: false, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'light', color: 'yellow', pill: false, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'light', color: 'green', pill: false, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'light', color: 'teal', pill: false, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'light', color: 'indigo', pill: false, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'light', color: 'blue', pill: false, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'light', color: 'purple', pill: false, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'light', color: 'pink', pill: false, outline: false, class: 'mx-1' },
                    ],
                    [
                        { size: 'md', theme: 'light', color: 'gray', pill: true, outline: false, class: null },
                        { size: 'md', theme: 'light', color: 'cool-gray', pill: true, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'light', color: 'red', pill: true, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'light', color: 'orange', pill: true, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'light', color: 'yellow', pill: true, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'light', color: 'green', pill: true, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'light', color: 'teal', pill: true, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'light', color: 'indigo', pill: true, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'light', color: 'blue', pill: true, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'light', color: 'purple', pill: true, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'light', color: 'pink', pill: true, outline: false, class: 'mx-1' },
                    ],
                    [
                        { size: 'md', theme: 'light', color: 'gray', pill: false, outline: true, class: null },
                        { size: 'md', theme: 'light', color: 'cool-gray', pill: false, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'light', color: 'red', pill: false, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'light', color: 'orange', pill: false, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'light', color: 'yellow', pill: false, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'light', color: 'green', pill: false, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'light', color: 'teal', pill: false, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'light', color: 'indigo', pill: false, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'light', color: 'blue', pill: false, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'light', color: 'purple', pill: false, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'light', color: 'pink', pill: false, outline: true, class: 'mx-1' },
                    ],
                    [
                        { size: 'md', theme: 'light', color: 'gray', pill: true, outline: true, class: null },
                        { size: 'md', theme: 'light', color: 'cool-gray', pill: true, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'light', color: 'red', pill: true, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'light', color: 'orange', pill: true, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'light', color: 'yellow', pill: true, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'light', color: 'green', pill: true, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'light', color: 'teal', pill: true, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'light', color: 'indigo', pill: true, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'light', color: 'blue', pill: true, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'light', color: 'purple', pill: true, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'light', color: 'pink', pill: true, outline: true, class: 'mx-1' },
                    ],
                    [
                        { size: 'md', theme: 'dark', color: 'gray', pill: false, outline: false, class: null },
                        { size: 'md', theme: 'dark', color: 'cool-gray', pill: false, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'dark', color: 'red', pill: false, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'dark', color: 'orange', pill: false, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'dark', color: 'yellow', pill: false, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'dark', color: 'green', pill: false, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'dark', color: 'teal', pill: false, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'dark', color: 'indigo', pill: false, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'dark', color: 'blue', pill: false, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'dark', color: 'purple', pill: false, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'dark', color: 'pink', pill: false, outline: false, class: 'mx-1' },
                    ],
                    [
                        { size: 'md', theme: 'dark', color: 'gray', pill: true, outline: false, class: null },
                        { size: 'md', theme: 'dark', color: 'cool-gray', pill: true, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'dark', color: 'red', pill: true, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'dark', color: 'orange', pill: true, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'dark', color: 'yellow', pill: true, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'dark', color: 'green', pill: true, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'dark', color: 'teal', pill: true, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'dark', color: 'indigo', pill: true, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'dark', color: 'blue', pill: true, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'dark', color: 'purple', pill: true, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'dark', color: 'pink', pill: true, outline: false, class: 'mx-1' },
                    ],
                    [
                        { size: 'md', theme: 'dark', color: 'gray', pill: false, outline: true, class: null },
                        { size: 'md', theme: 'dark', color: 'cool-gray', pill: false, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'dark', color: 'red', pill: false, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'dark', color: 'orange', pill: false, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'dark', color: 'yellow', pill: false, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'dark', color: 'green', pill: false, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'dark', color: 'teal', pill: false, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'dark', color: 'indigo', pill: false, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'dark', color: 'blue', pill: false, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'dark', color: 'purple', pill: false, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'dark', color: 'pink', pill: false, outline: true, class: 'mx-1' },
                    ],
                    [
                        { size: 'md', theme: 'dark', color: 'gray', pill: true, outline: true, class: null },
                        { size: 'md', theme: 'dark', color: 'cool-gray', pill: true, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'dark', color: 'red', pill: true, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'dark', color: 'orange', pill: true, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'dark', color: 'yellow', pill: true, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'dark', color: 'green', pill: true, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'dark', color: 'teal', pill: true, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'dark', color: 'indigo', pill: true, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'dark', color: 'blue', pill: true, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'dark', color: 'purple', pill: true, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'dark', color: 'pink', pill: true, outline: true, class: 'mx-1' },
                    ],
                    [
                        { size: 'md', theme: 'darker', color: 'gray', pill: false, outline: false, class: null },
                        { size: 'md', theme: 'darker', color: 'cool-gray', pill: false, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'darker', color: 'red', pill: false, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'darker', color: 'orange', pill: false, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'darker', color: 'yellow', pill: false, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'darker', color: 'green', pill: false, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'darker', color: 'teal', pill: false, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'darker', color: 'indigo', pill: false, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'darker', color: 'blue', pill: false, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'darker', color: 'purple', pill: false, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'darker', color: 'pink', pill: false, outline: false, class: 'mx-1' },
                    ],
                    [
                        { size: 'md', theme: 'darker', color: 'gray', pill: true, outline: false, class: null },
                        { size: 'md', theme: 'darker', color: 'cool-gray', pill: true, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'darker', color: 'red', pill: true, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'darker', color: 'orange', pill: true, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'darker', color: 'yellow', pill: true, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'darker', color: 'green', pill: true, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'darker', color: 'teal', pill: true, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'darker', color: 'indigo', pill: true, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'darker', color: 'blue', pill: true, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'darker', color: 'purple', pill: true, outline: false, class: 'mx-1' },
                        { size: 'md', theme: 'darker', color: 'pink', pill: true, outline: false, class: 'mx-1' },
                    ],
                    [
                        { size: 'md', theme: 'darker', color: 'gray', pill: false, outline: true, class: null },
                        { size: 'md', theme: 'darker', color: 'cool-gray', pill: false, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'darker', color: 'red', pill: false, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'darker', color: 'orange', pill: false, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'darker', color: 'yellow', pill: false, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'darker', color: 'green', pill: false, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'darker', color: 'teal', pill: false, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'darker', color: 'indigo', pill: false, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'darker', color: 'blue', pill: false, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'darker', color: 'purple', pill: false, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'darker', color: 'pink', pill: false, outline: true, class: 'mx-1' },
                    ],
                    [
                        { size: 'md', theme: 'darker', color: 'gray', pill: true, outline: true, class: null },
                        { size: 'md', theme: 'darker', color: 'cool-gray', pill: true, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'darker', color: 'red', pill: true, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'darker', color: 'orange', pill: true, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'darker', color: 'yellow', pill: true, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'darker', color: 'green', pill: true, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'darker', color: 'teal', pill: true, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'darker', color: 'indigo', pill: true, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'darker', color: 'blue', pill: true, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'darker', color: 'purple', pill: true, outline: true, class: 'mx-1' },
                        { size: 'md', theme: 'darker', color: 'pink', pill: true, outline: true, class: 'mx-1' },
                    ],
                    [
                        { size: 'lg', theme: 'light', color: 'gray', pill: false, outline: false, class: null },
                        { size: 'lg', theme: 'light', color: 'cool-gray', pill: false, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'light', color: 'red', pill: false, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'light', color: 'orange', pill: false, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'light', color: 'yellow', pill: false, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'light', color: 'green', pill: false, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'light', color: 'teal', pill: false, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'light', color: 'indigo', pill: false, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'light', color: 'blue', pill: false, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'light', color: 'purple', pill: false, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'light', color: 'pink', pill: false, outline: false, class: 'mx-1' },
                    ],
                    [
                        { size: 'lg', theme: 'light', color: 'gray', pill: true, outline: false, class: null },
                        { size: 'lg', theme: 'light', color: 'cool-gray', pill: true, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'light', color: 'red', pill: true, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'light', color: 'orange', pill: true, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'light', color: 'yellow', pill: true, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'light', color: 'green', pill: true, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'light', color: 'teal', pill: true, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'light', color: 'indigo', pill: true, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'light', color: 'blue', pill: true, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'light', color: 'purple', pill: true, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'light', color: 'pink', pill: true, outline: false, class: 'mx-1' },
                    ],
                    [
                        { size: 'lg', theme: 'light', color: 'gray', pill: false, outline: true, class: null },
                        { size: 'lg', theme: 'light', color: 'cool-gray', pill: false, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'light', color: 'red', pill: false, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'light', color: 'orange', pill: false, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'light', color: 'yellow', pill: false, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'light', color: 'green', pill: false, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'light', color: 'teal', pill: false, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'light', color: 'indigo', pill: false, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'light', color: 'blue', pill: false, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'light', color: 'purple', pill: false, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'light', color: 'pink', pill: false, outline: true, class: 'mx-1' },
                    ],
                    [
                        { size: 'lg', theme: 'light', color: 'gray', pill: true, outline: true, class: null },
                        { size: 'lg', theme: 'light', color: 'cool-gray', pill: true, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'light', color: 'red', pill: true, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'light', color: 'orange', pill: true, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'light', color: 'yellow', pill: true, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'light', color: 'green', pill: true, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'light', color: 'teal', pill: true, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'light', color: 'indigo', pill: true, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'light', color: 'blue', pill: true, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'light', color: 'purple', pill: true, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'light', color: 'pink', pill: true, outline: true, class: 'mx-1' },
                    ],
                    [
                        { size: 'lg', theme: 'dark', color: 'gray', pill: false, outline: false, class: null },
                        { size: 'lg', theme: 'dark', color: 'cool-gray', pill: false, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'dark', color: 'red', pill: false, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'dark', color: 'orange', pill: false, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'dark', color: 'yellow', pill: false, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'dark', color: 'green', pill: false, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'dark', color: 'teal', pill: false, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'dark', color: 'indigo', pill: false, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'dark', color: 'blue', pill: false, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'dark', color: 'purple', pill: false, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'dark', color: 'pink', pill: false, outline: false, class: 'mx-1' },
                    ],
                    [
                        { size: 'lg', theme: 'dark', color: 'gray', pill: true, outline: false, class: null },
                        { size: 'lg', theme: 'dark', color: 'cool-gray', pill: true, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'dark', color: 'red', pill: true, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'dark', color: 'orange', pill: true, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'dark', color: 'yellow', pill: true, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'dark', color: 'green', pill: true, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'dark', color: 'teal', pill: true, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'dark', color: 'indigo', pill: true, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'dark', color: 'blue', pill: true, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'dark', color: 'purple', pill: true, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'dark', color: 'pink', pill: true, outline: false, class: 'mx-1' },
                    ],
                    [
                        { size: 'lg', theme: 'dark', color: 'gray', pill: false, outline: true, class: null },
                        { size: 'lg', theme: 'dark', color: 'cool-gray', pill: false, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'dark', color: 'red', pill: false, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'dark', color: 'orange', pill: false, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'dark', color: 'yellow', pill: false, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'dark', color: 'green', pill: false, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'dark', color: 'teal', pill: false, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'dark', color: 'indigo', pill: false, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'dark', color: 'blue', pill: false, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'dark', color: 'purple', pill: false, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'dark', color: 'pink', pill: false, outline: true, class: 'mx-1' },
                    ],
                    [
                        { size: 'lg', theme: 'dark', color: 'gray', pill: true, outline: true, class: null },
                        { size: 'lg', theme: 'dark', color: 'cool-gray', pill: true, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'dark', color: 'red', pill: true, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'dark', color: 'orange', pill: true, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'dark', color: 'yellow', pill: true, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'dark', color: 'green', pill: true, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'dark', color: 'teal', pill: true, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'dark', color: 'indigo', pill: true, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'dark', color: 'blue', pill: true, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'dark', color: 'purple', pill: true, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'dark', color: 'pink', pill: true, outline: true, class: 'mx-1' },
                    ],
                    [
                        { size: 'lg', theme: 'darker', color: 'gray', pill: false, outline: false, class: null },
                        { size: 'lg', theme: 'darker', color: 'cool-gray', pill: false, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'darker', color: 'red', pill: false, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'darker', color: 'orange', pill: false, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'darker', color: 'yellow', pill: false, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'darker', color: 'green', pill: false, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'darker', color: 'teal', pill: false, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'darker', color: 'indigo', pill: false, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'darker', color: 'blue', pill: false, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'darker', color: 'purple', pill: false, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'darker', color: 'pink', pill: false, outline: false, class: 'mx-1' },
                    ],
                    [
                        { size: 'lg', theme: 'darker', color: 'gray', pill: true, outline: false, class: null },
                        { size: 'lg', theme: 'darker', color: 'cool-gray', pill: true, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'darker', color: 'red', pill: true, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'darker', color: 'orange', pill: true, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'darker', color: 'yellow', pill: true, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'darker', color: 'green', pill: true, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'darker', color: 'teal', pill: true, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'darker', color: 'indigo', pill: true, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'darker', color: 'blue', pill: true, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'darker', color: 'purple', pill: true, outline: false, class: 'mx-1' },
                        { size: 'lg', theme: 'darker', color: 'pink', pill: true, outline: false, class: 'mx-1' },
                    ],
                    [
                        { size: 'lg', theme: 'darker', color: 'gray', pill: false, outline: true, class: null },
                        { size: 'lg', theme: 'darker', color: 'cool-gray', pill: false, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'darker', color: 'red', pill: false, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'darker', color: 'orange', pill: false, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'darker', color: 'yellow', pill: false, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'darker', color: 'green', pill: false, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'darker', color: 'teal', pill: false, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'darker', color: 'indigo', pill: false, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'darker', color: 'blue', pill: false, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'darker', color: 'purple', pill: false, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'darker', color: 'pink', pill: false, outline: true, class: 'mx-1' },
                    ],
                    [
                        { size: 'lg', theme: 'darker', color: 'gray', pill: true, outline: true, class: null },
                        { size: 'lg', theme: 'darker', color: 'cool-gray', pill: true, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'darker', color: 'red', pill: true, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'darker', color: 'orange', pill: true, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'darker', color: 'yellow', pill: true, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'darker', color: 'green', pill: true, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'darker', color: 'teal', pill: true, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'darker', color: 'indigo', pill: true, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'darker', color: 'blue', pill: true, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'darker', color: 'purple', pill: true, outline: true, class: 'mx-1' },
                        { size: 'lg', theme: 'darker', color: 'pink', pill: true, outline: true, class: 'mx-1' },
                    ],
                    [
                        { size: 'xl', theme: 'light', color: 'gray', pill: false, outline: false, class: null },
                        { size: 'xl', theme: 'light', color: 'cool-gray', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'light', color: 'red', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'light', color: 'orange', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'light', color: 'yellow', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'light', color: 'green', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'light', color: 'teal', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'light', color: 'indigo', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'light', color: 'blue', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'light', color: 'purple', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'light', color: 'pink', pill: false, outline: false, class: 'mx-1' },
                    ],
                    [
                        { size: 'xl', theme: 'light', color: 'gray', pill: true, outline: false, class: null },
                        { size: 'xl', theme: 'light', color: 'cool-gray', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'light', color: 'red', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'light', color: 'orange', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'light', color: 'yellow', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'light', color: 'green', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'light', color: 'teal', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'light', color: 'indigo', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'light', color: 'blue', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'light', color: 'purple', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'light', color: 'pink', pill: true, outline: false, class: 'mx-1' },
                    ],
                    [
                        { size: 'xl', theme: 'light', color: 'gray', pill: false, outline: true, class: null },
                        { size: 'xl', theme: 'light', color: 'cool-gray', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'light', color: 'red', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'light', color: 'orange', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'light', color: 'yellow', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'light', color: 'green', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'light', color: 'teal', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'light', color: 'indigo', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'light', color: 'blue', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'light', color: 'purple', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'light', color: 'pink', pill: false, outline: true, class: 'mx-1' },
                    ],
                    [
                        { size: 'xl', theme: 'light', color: 'gray', pill: true, outline: true, class: null },
                        { size: 'xl', theme: 'light', color: 'cool-gray', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'light', color: 'red', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'light', color: 'orange', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'light', color: 'yellow', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'light', color: 'green', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'light', color: 'teal', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'light', color: 'indigo', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'light', color: 'blue', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'light', color: 'purple', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'light', color: 'pink', pill: true, outline: true, class: 'mx-1' },
                    ],
                    [
                        { size: 'xl', theme: 'dark', color: 'gray', pill: false, outline: false, class: null },
                        { size: 'xl', theme: 'dark', color: 'cool-gray', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'dark', color: 'red', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'dark', color: 'orange', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'dark', color: 'yellow', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'dark', color: 'green', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'dark', color: 'teal', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'dark', color: 'indigo', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'dark', color: 'blue', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'dark', color: 'purple', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'dark', color: 'pink', pill: false, outline: false, class: 'mx-1' },
                    ],
                    [
                        { size: 'xl', theme: 'dark', color: 'gray', pill: true, outline: false, class: null },
                        { size: 'xl', theme: 'dark', color: 'cool-gray', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'dark', color: 'red', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'dark', color: 'orange', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'dark', color: 'yellow', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'dark', color: 'green', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'dark', color: 'teal', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'dark', color: 'indigo', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'dark', color: 'blue', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'dark', color: 'purple', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'dark', color: 'pink', pill: true, outline: false, class: 'mx-1' },
                    ],
                    [
                        { size: 'xl', theme: 'dark', color: 'gray', pill: false, outline: true, class: null },
                        { size: 'xl', theme: 'dark', color: 'cool-gray', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'dark', color: 'red', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'dark', color: 'orange', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'dark', color: 'yellow', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'dark', color: 'green', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'dark', color: 'teal', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'dark', color: 'indigo', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'dark', color: 'blue', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'dark', color: 'purple', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'dark', color: 'pink', pill: false, outline: true, class: 'mx-1' },
                    ],
                    [
                        { size: 'xl', theme: 'dark', color: 'gray', pill: true, outline: true, class: null },
                        { size: 'xl', theme: 'dark', color: 'cool-gray', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'dark', color: 'red', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'dark', color: 'orange', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'dark', color: 'yellow', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'dark', color: 'green', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'dark', color: 'teal', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'dark', color: 'indigo', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'dark', color: 'blue', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'dark', color: 'purple', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'dark', color: 'pink', pill: true, outline: true, class: 'mx-1' },
                    ],
                    [
                        { size: 'xl', theme: 'darker', color: 'gray', pill: false, outline: false, class: null },
                        { size: 'xl', theme: 'darker', color: 'cool-gray', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'darker', color: 'red', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'darker', color: 'orange', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'darker', color: 'yellow', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'darker', color: 'green', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'darker', color: 'teal', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'darker', color: 'indigo', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'darker', color: 'blue', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'darker', color: 'purple', pill: false, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'darker', color: 'pink', pill: false, outline: false, class: 'mx-1' },
                    ],
                    [
                        { size: 'xl', theme: 'darker', color: 'gray', pill: true, outline: false, class: null },
                        { size: 'xl', theme: 'darker', color: 'cool-gray', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'darker', color: 'red', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'darker', color: 'orange', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'darker', color: 'yellow', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'darker', color: 'green', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'darker', color: 'teal', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'darker', color: 'indigo', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'darker', color: 'blue', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'darker', color: 'purple', pill: true, outline: false, class: 'mx-1' },
                        { size: 'xl', theme: 'darker', color: 'pink', pill: true, outline: false, class: 'mx-1' },
                    ],
                    [
                        { size: 'xl', theme: 'darker', color: 'gray', pill: false, outline: true, class: null },
                        { size: 'xl', theme: 'darker', color: 'cool-gray', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'darker', color: 'red', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'darker', color: 'orange', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'darker', color: 'yellow', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'darker', color: 'green', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'darker', color: 'teal', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'darker', color: 'indigo', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'darker', color: 'blue', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'darker', color: 'purple', pill: false, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'darker', color: 'pink', pill: false, outline: true, class: 'mx-1' },
                    ],
                    [
                        { size: 'xl', theme: 'darker', color: 'gray', pill: true, outline: true, class: null },
                        { size: 'xl', theme: 'darker', color: 'cool-gray', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'darker', color: 'red', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'darker', color: 'orange', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'darker', color: 'yellow', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'darker', color: 'green', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'darker', color: 'teal', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'darker', color: 'indigo', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'darker', color: 'blue', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'darker', color: 'purple', pill: true, outline: true, class: 'mx-1' },
                        { size: 'xl', theme: 'darker', color: 'pink', pill: true, outline: true, class: 'mx-1' },
                    ],
                ],
            };
        },

        methods: {},
    };
</script>
